### ISSUE TITLE
Attachment tool displays "Error: Missing IRI for NamedNode" error

### ISSUE THREAD

**Issue by kevin-howard-jd** [solid/meeting-pane#23]
If I click the <img src="https://solid.github.io/solid-ui/src/icons/noun_25830.svg" alt="Attachment" width="16"> Attachment tool, a "Error: Missing IRI for NamedNode" error is displayed.

## To Replicate
1. Open a Meeting pane (e.g., https://michielbdejong.inrupt.net/public/example-meeting/index.ttl#this)
2. Click on the Attachment tool.

## Expected
1. I can access the Attachment functionality.

## Actual
1. An error is displayed:
```
Error: Missing IRI for NamedNode
  undefined
    Error: Missing IRI for NamedNode  undefined
        at new t (https://michielbdejong.inrupt.net/mashlib.min.js:8:105004)  undefined
        at t.value (https://michielbdejong.inrupt.net/mashlib.min.js:398:156469)  undefined
        at w (https://michielbdejong.inrupt.net/mashlib.min.js:16:1340)  undefined
        at https://michielbdejong.inrupt.net/mashlib.min.js:16:1805  undefined
        at x (https://michielbdejong.inrupt.net/mashlib.min.js:16:1906)  undefined
        at Object.render (https://michielbdejong.inrupt.net/mashlib.min.js:16:2290)  undefined
        at https://michielbdejong.inrupt.net/mashlib.min.js:216:8347  undefined
        at HTMLImageElement.<anonymous> (https://michielbdejong.inrupt.net/mashlib.min.js:216:8819)
```

**Comment by kevin-howard-jd** [comment]
Duplicate of https://github.com/solid/meeting-pane/issues/13
